ai/urls.py
from django.urls import path
from ai import views
from ai import models

app_name = "ai"

urlpatterns = [
    # chats (ai to user messaging)
    path("chats/", views.ChatsView.as_view(), name="chats"),
    path(
        "chat-messages/<uuid:chat_pk>/",
        views.ChatMessagesView.as_view(),
        name="chat-messages",
    ),
]

urlpatterns.extend(models.AI.get_urls())
urlpatterns.extend(models.AISettings.get_urls())
urlpatterns.extend(models.Chat.get_urls())
urlpatterns.extend(models.Message.get_urls())

economics_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("users.urls", namespace="users")),
    path("ai/", include("ai.urls", namespace="ai")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    # path("profile", views.ProfileView.as_view(), name="profile"),
    # other paths
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """search history stoored and presented locally"""
    pass

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class UserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class UserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )

users/views/home.py
from django.views.generic import TemplateView
import logging

logger = logging.getLogger(__name__)


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

users/views/signup.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model

from users.forms import UserCreationForm


User = get_user_model()


class SignupPageView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

users/templates/_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}economics dashboard{% endblock title %}</title>

    <!-- Pico CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

    <!-- JS Scripts -->
    <script src="https://code.jquery.com/jquery-3.6.4.js" integrity="sha256-a9jBBRygX1Bh5lt8GZjXDzyOB+bWve9EiO7tROUtj/E=" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/htmx.org@2.0.3"></script>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
 
    <!-- Custom Styles -->
    <style>
      body {
        font-family: 'Rubik', sans-serif;
      }

      /* Navbar Styling */
      nav {
        background: linear-gradient(135deg, var(--background-dark), var(--midnight-purple));
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
        border-radius: 0.5rem;
      }

      nav ul li a {
        font-weight: 500;
        border-radius: 5px;
        color: var(--background-light);
        transition: background-color 0.3s, color 0.3s ease;
        cursor: pointer;
      }

      nav ul li a:hover {
        background-color: var(--deep-purple);
        color: var(--soft-pink);
        text-decoration: none;
      }

      nav ul li a.active {
        background-color: var(--accent-color);
        color: var(--background-dark);
      }

      /* Footer Styling */
      footer {
        text-align: center;
        padding: 1rem 0;
        background-color: var(--background-dark);
        color: var(--background-light);
      }

      /* Input Styling */
      input#search-query:focus {
        border: 2px solid var(--deep-purple);
        box-shadow: 0 0 10px rgba(94, 129, 172, 0.5);
      }
    </style>
  </head>
  <body>
    <header class="container">
      <nav class="grid" style="padding-left: 11px">
        <ul>
          <li><strong><a 
            hx-get="{% url 'home' %}" 
            hx-target="#body" 
            hx-swap="innerHTML transition:true"
            hx-push-url="true">Economics Dashboard</a></strong></li>
          {% if user.is_authenticated %}
            <li><a 
              hx-get="{% url 'account_logout' %}" 
              hx-target="body" 
              hx-swap="outerHTML transition:true"
              hx-push-url="true">log out</a></li>
          {% else %}
            <li><a 
              hx-get="{% url 'account_login' %}" 
              hx-target="body" 
              hx-swap="outerHTML transition:true"
              hx-push-url="true">log in</a></li>
            <li><a 
              hx-get="{% url 'account_signup' %}" 
              hx-target="body" 
              hx-swap="outerHTML transition:true"
              hx-push-url="true">sign up</a></li>
          {% endif %}
          <li><a 
            hx-target="#body" 
            hx-swap="innerHTML transition:true"
            hx-push-url="true">how to use?</a></li>
        </ul>
      </nav>
    </header>

    <main id="body" class="container">
      <section>
        {% block content %}
        {% endblock content %}
      </section>
    </main>

    <footer class="container">
      <small>All rights reserved.</small>
    </footer>
  </body>
</html>

users/templates/about.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "partials/about.html" %}
{% endblock %}

users/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}economics dashboard{% endblock title %}</title>

    <!-- Pico CSS -->
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.min.css"
    >

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@400;500;700&display=swap" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css" rel="stylesheet">

    <!-- JS Scripts -->
    <script src="https://unpkg.com/htmx.org@2.0.3"></script>
    <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
    <script src="{% static 'js/base.js' %}"></script>
 
    <!-- Custom Styles -->
    <style>
      body {
        font-family: 'Rubik', sans-serif;
      }

      /* Navbar Styling */
      nav {
        background: linear-gradient(135deg, var(--background-dark), var(--midnight-purple));
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.2);
        border-radius: 0.5rem;
      }

      nav ul li a {
        font-weight: 500;
        border-radius: 5px;
        color: var(--background-light);
        transition: background-color 0.3s, color 0.3s ease;
        cursor: pointer;
      }

      nav ul li a:hover {
        background-color: var(--deep-purple);
        color: var(--soft-pink);
        text-decoration: none;
      }

      nav ul li a.active {
        background-color: var(--accent-color);
        color: var(--background-dark);
      }

      /* Footer Styling */
      footer {
        text-align: center;
        padding: 1rem 0;
        background-color: var(--background-dark);
        color: var(--background-light);
      }

      /* Input Styling */
      input#search-query:focus {
        border: 2px solid var(--deep-purple);
        box-shadow: 0 0 10px rgba(94, 129, 172, 0.5);
      }
    </style>
  </head>
  <body>
    <header class="container">
      <nav class="grid" style="padding-left: 11px">
        <ul>
          <li><strong><a 
            hx-get="{% url 'users:home' %}" 
            hx-target="body" 
            hx-swap="innerHTML transition:true"
            hx-push-url="true">Economics Dashboard</a></strong></li>
          {% if user.is_authenticated %}
            <li><a 
              hx-get="{% url 'account_logout' %}" 
              hx-target="#body" 
              hx-swap="innerHTML transition:true"
              hx-push-url="true">log out</a></li>
          {% else %}
            <li><a 
              hx-get="{% url 'account_login' %}" 
              hx-target="#body" 
              hx-swap="innerHTML transition:true"
              hx-push-url="true">log in</a></li>
            <li><a 
              hx-get="{% url 'account_signup' %}" 
              hx-target="#body" 
              hx-swap="innerHTML transition:true"
              hx-push-url="true">sign up</a></li>
          {% endif %}
          <li><a 
            hx-target="#body" 
            hx-swap="innerHTML transition:true"
            hx-push-url="true">how to use?</a></li>
        </ul>
      </nav>
    </header>

    <main id="body" class="container">
      <section>
        {% block content %}
        {% endblock content %}
      </section>
    </main>

    <footer class="container">
      <small>All rights reserved.</small>
    </footer>
  </body>
</html>

users/templates/home.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    {% include "partials/home.html" %}
{% endblock %}

{% block title %}kalibre{% endblock title %}

users/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}My Profile{% endblock title %}

{% block content %}

empty profile.

{% endblock content %}