ai/urls.py
from django.urls import path
from ai import views
from ai import models

app_name = "ai"

urlpatterns = [
    # chats (ai to user messaging)
    path("chats/", views.ChatsView.as_view(), name="chats"),
    path(
        "chat-messages/<uuid:chat_pk>/",
        views.ChatMessagesView.as_view(),
        name="chat-messages",
    ),
]

urlpatterns.extend(models.AI.get_urls())
urlpatterns.extend(models.AISettings.get_urls())
urlpatterns.extend(models.Chat.get_urls())
urlpatterns.extend(models.Message.get_urls())

dashboard/urls.py
from django.urls import path
from dashboard import views


app_name = "dashboard"

urlpatterns = [
    path("", views.DashboardView.as_view(), name="dashboard"),
]

economics_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("", include("users.urls", namespace="users")),
    path("ai/", include("ai.urls", namespace="ai")),
    path("dashboard/", include("dashboard.urls", namespace="dashboard")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    # path("profile", views.ProfileView.as_view(), name="profile"),
    # other paths
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """search history stoored and presented locally"""
    pass

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms


class UserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )


class UserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "email",
            "username",
        )

users/views/home.py
from django.views.generic import TemplateView
import logging

logger = logging.getLogger(__name__)


class HomeView(TemplateView):
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

users/views/signup.py
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import get_user_model

from users.forms import UserCreationForm


User = get_user_model()


class SignupPageView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "accounts/signup.html"

users/templates/partials/about.html
<!--about.html-->
<div
    hx-trigger="refresh-forms-about from:body"
    hx-get="{% url 'about' %}"
    hx-swap="outerHTML transition:true"
>
    <header class="about-container">
        <hgroup>
            <h2>About Kalibre!</h2>
        </hgroup>
    </header>

    <main class="container grid">
        <!-- How To Use Section -->
        <details open>
            <summary role="button">How to Use Kalibre?</summary>
            <article class="instructions-section">
                <ul>
                    <li>Create an account or log in if you already have one.</li>
                    <li>Add email addresses to which you'd like to send your ebooks in 'my emails'.</li>
                    <li>Click 'kalibre' in the upper-left corner to return to the book search page.</li>
                    <li>Find your book and send it with a simple click!</li>
                </ul>

                <h5>Send Books Directly to Your Kindle:</h5>
                <ul>
                    <li>Login to your Amazon account.</li>
                    <li>Go to 'Manage Your Content and Devices'.</li>
                    <li>Under 'Preferences', find 'Personal Document Settings'.</li>
                    <li>Add <i>bllendev@gmail.com</i> to 'Approved Personal Document E-mail List'.</li>
                </ul>
            </article>
        </details>

        <!-- Acknowledgments Section -->
        <details>
            <summary role="button">Acknowledgments</summary>
            <article class="acknowledgment-section">
                <ul>
                    <li>Special thanks to <i>pine</i> for the amazing artwork.</li>
                    <li>Gratitude to <i>harrison-broadbent</i> for <i>libgen-api</i>. We use a modified version of this package.</li>
                </ul>

                <figure>
                    <img 
                        src="https://res.cloudinary.com/dmh0kulu1/image/upload/c_crop,h_1819/v1669002136/Animated-GIF-Export_1_cvc2cn.gif" 
                        alt="Coffee Sip Animation"
                        style="max-width:45%; height:auto; border-radius: 8px;"
                    >
                    <figcaption>Enjoy a sip while using Kalibre!</figcaption>
                </figure>
            </article>
        </details>
    </main>
</div>

users/templates/partials/home.html
<div class="text-center">
    <h1 class="title" style="font-size: 3rem; color: var(--primary);">economics dashboard</h1>
    <div hx-get="{% url 'dashboard:dashboard' %}"
        hx-trigger="load"
        hx-swap="innerHTML"
        hx-target="this"
    ></div>
</div>